name: Build application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows
        run: |
          pyinstaller --onefile --name AutoclickerX.exe --icon=assets/logo_mouse.ico --version-file=version.txt --noconsole --clean --onefile main.py

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AutoclickerX-Windows
          path: dist/AutoclickerX.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          pip install -r requirements.txt

      - name: Build Linux
        run: |
          pyinstaller --onefile --name AutoclickerX --icon=assets/logo_mouse.ico --version-file=version.txt --noconsole --clean --onefile main.py

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AutoclickerX-Linux
          path: dist/AutoclickerX

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build macOS
        run: |
          pyinstaller --onefile --name AutoclickerX --icon=assets/logo_mouse.ico --version-file=version.txt --noconsole --clean --onefile main.py

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AutoclickerX-macOS
          path: dist/AutoclickerX

  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts
  
      - name: Create GitHub Release with Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          body: |
            This release includes the latest build artifacts.
          draft: true
          prerelease: true
          files: |
            artifacts/AutoclickerX-Windows/AutoclickerX.exe
            artifacts/AutoclickerX-Linux/AutoclickerX
            artifacts/AutoclickerX-macOS/AutoclickerX
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
