name: Build application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: AutoclickerX-Windows
            output_path: dist/AutoclickerX.exe
            output_name: AutoclickerX.exe
          - os: ubuntu-latest
            artifact_name: AutoclickerX-Linux
            output_path: dist/autoclickerx-linux
            output_name: autoclickerx-linux
          - os: macos-latest
            artifact_name: AutoclickerX-Mac
            output_path: dist/autoclickerx-mac
            output_name: autoclickerx-mac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then sudo apt update; fi
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Build executable
        run: |
          pyinstaller --onefile --name ${{ matrix.output_name }} --icon=assets/logo_mouse.ico --version-file=version.txt --noconsole --clean main.py
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.output_path }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts

      - name: Create GitHub Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          body: |
            This release includes the latest build artifacts.
          draft: true
          prerelease: true
          files: |
            artifacts/AutoclickerX-Windows/AutoclickerX.exe
            artifacts/AutoclickerX-Linux/autoclickerx-linux
            artifacts/AutoclickerX-Mac/autoclickerx-mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
